[package]
name = "create_your_controls"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true
publish.workspace = true
license.workspace = true
homepage.workspace = true
readme.workspace = true

[lib]
path = "src/create_your_controls.rs"

[dependencies]
gpui.workspace = true

[lints]
workspace = true
